### ISSUE TITLE
Could you please reveal the division of these downstream task datasets

### ISSUE THREAD

**Issue by icey-zhang** [ElementAI/seasonal-contrast#4]
I try to conduct downstream tasks, and I download the different datasets. But the training needs the division of training and test sets: train.txt, val.txt and test.txt. Could you please reveal the division of these data sets?

**Comment by icey-zhang** [comment]
I have found the division from https://github.com/yerkojahve/Meta-Pseudo-label/tree/44a7cbc6429505f6e54fee432a78be4a84c9d144/remote_sensing_representations

**Comment by oscmansan** [comment]
Hi @icey-zhang, thanks for reaching out. We use the data splits provided here: https://github.com/google-research/google-research/tree/master/remote_sensing_representations. Hope this helps!
